# Generated by Django 5.0.6 on 2024-05-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_meal_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='food',
            field=models.ManyToManyField(related_name='restaurants', to='apis.food'),
        ),
    ]
