# Generated by Django 5.0.6 on 2024-05-19 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_restaurant_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unis', to='apis.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
