# Generated by Django 5.0.6 on 2024-05-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_uni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uni',
            name='restaurant',
        ),
    ]
