# Generated by Django 5.0.6 on 2024-05-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_remove_uni_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='uni',
            name='restaurant',
            field=models.ManyToManyField(related_name='unis', to='apis.restaurant'),
        ),
    ]
