# Generated by Django 5.0.6 on 2024-05-19 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_remove_uni_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='uni',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unis', to='apis.restaurant'),
        ),
    ]
