# Generated by Django 5.0.6 on 2024-05-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField(auto_created=125689215)),
                ('payment_amount', models.IntegerField(default=0)),
                ('payment_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
