# Generated by Django 5.0.6 on 2024-05-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_financial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financial',
            name='payment_id',
        ),
    ]
