# Generated by Django 5.0.6 on 2024-05-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_remove_financial_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial',
            name='payment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
